FROM postgres:9.6

# Set environment variables
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB postgres

# add a COPY line for each SQL to run on startup
# COPY <filename>.sql /docker-entrypoint-initdb.d/<filename>.sql
